name = "Bench"
uuid = "5e75a500-5f15-4344-bbc6-cbb171970aee"
authors = ["Kolia Sadeghi <ksadeghi@princeton.edu>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
